#!/bin/bash

# Update the package list and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy to distribute traffic to web-01 and web-02 using round-robin
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 54.237.26.187:80 check
    server web-02 100.26.238.237:80 check
EOF

# Enable HAProxy to be managed via init script
sudo systemctl enable haproxy

# Restart HAProxy to apply the configuration
sudo systemctl restart haproxy
