#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# Script that only displays username, user id, and Home directory path for the user

while read -r passwd;
do
    echo "$passwd" | cut -d ":" -f1,2,6
done < "/etc/passwd"
