#!/usr/bin/env bash
# This script connects to the server using the private key ~/.ssh/school and the user ubuntu.

# Use ssh with the private key and the user ubuntu
ssh -i ~/.ssh/school ubuntu@server01
